team_list = ["Argentina",
             "Australia",
             "Belgium",
             "Brazil",
             "Colombia",
             "Costa Rica",
             "Croatia",
             "Denmark",
             "Egypt",
             "England",
             "France",
             "Germany",
             "Iceland",
             "Iran",
             "Japan",
             "Korea Republic",
             "Mexico",
             "Morocco",
             "Nigeria",
             "Panama",
             "Peru",
             "Poland",
             "Portugal",
             "Russia",
             "Saudi Arabia",
             "Senegal",
             "Serbia",
             "Spain",
             "Sweden",
             "Switzerland ",
             "Tunisia",
             "Uruguay"]


city_list = ['Bucharest',
             "Arad",
             "Baia Mare",
             "Blaj",
             "Bucharest",
             "Cluj-Napoca",
             "Craiova",
             "Dej",
             "Deva",
             "Giurgiu",
             "Hunedoara",
             "Lugoj",
             "Mangalia",
             "Oradea",
             "Reghin",
             "Slatina",
             "Slobozia",
             "Timisoara",
             "Tulcea",
             "Turda",
             "Vaslui"]


apparance_list = ["attractive",
                  "bald",
                  "beautiful",
                  "chubby",
                  "clean",
                  "dazzling",
                  "drab",
                  "elegant",
                  "fancy",
                  "fit",
                  "flabby",
                  "glamorous",
                  "gorgeous",
                  "handsome",
                  "long",
                  "magnificent",
                  "muscular",
                  "plain",
                  "plump",
                  "quaint",
                  "scruffy",
                  "shapely",
                  "short",
                  "skinny",
                  "stocky",
                  "ugly",
                  "unkempt",
                  "unsightly"]

color_list = ["ashy",
              "black",
              "blue",
              "gray",
              "green",
              "icy",
              "lemon",
              "mango",
              "orange",
              "purple",
              "red",
              "salmon",
              "white",
              "yellow"]


condition_list = ["alive",
                  "better",
                  "careful",
                  "clever",
                  "dead",
                  "easy",
                  "famous",
                  "gifted",
                  "hallowed",
                  "helpful",
                  "important",
                  "inexpensive",
                  "mealy",
                  "mushy",
                  "odd",
                  "poor",
                  "powerful",
                  "rich",
                  "shy",
                  "tender",
                  "unimportant",
                  "uninterested",
                  "vast",
                  "wrong"]


positive_personality_list = ["aggressive",
                             "agreeable",
                             "ambitious",
                             "brave",
                             "calm",
                             "delightful",
                             "eager",
                             "faithful",
                             "gentle",
                             "happy",
                             "jolly",
                             "kind",
                             "lively",
                             "nice",
                             "obedient",
                             "polite",
                             "proud",
                             "silly",
                             "thankful",
                             "victorious",
                             "witty",
                             "wonderful",
                             "zealous"]



negative_personality_list = ["angry",
                             "bewildered",
                             "clumsy",
                             "defeated",
                             "embarrassed",
                             "fierce",
                             "grumpy",
                             "helpless",
                             "itchy",
                             "jealous",
                             "lazy",
                             "mysterious",
                             "nervous",
                             "obnoxious",
                             "panicky",
                             "pitiful",
                             "repulsive",
                             "scary",
                             "thoughtless",
                             "uptight",
                             "worried"]

all_attributes = apparance_list + color_list + condition_list + positive_personality_list + negative_personality_list

male_names = ['James',
              'John',
              'Robert',
              'Michael',
              'William',
              'David',
              'Richard',
              'Charles',
              'Joseph',
              'Thomas',
              'Christopher',
              'Daniel',
              'Paul',
              'Mark',
              'Donald',
              'George',
              'Kenneth',
              'Steven',
              'Edward',
              'Brian',
              'Ronald',
              'Anthony',
              'Kevin',
              'Jason',
              'Matthew',
              'Gary',
              'Timothy',
              'Jose',
              'Larry',
              'Jeffrey',
              'Frank',
              'Scott',
              'Eric',
              'Stephen',
              'Andrew',
              'Raymond',
              'Gregory',
              'Joshua',
              'Jerry',
              'Dennis',
              'Walter',
              'Patrick',
              'Peter',
              'Harold',
              'Douglas',
              'Henry',
              'Carl',
              'Arthur',
              'Ryan',
              'Roger',
              'Joe',
              'Juan',
              'Jack',
              'Albert',
              'Jonathan',
              'Justin',
              'Terry',
              'Gerald',
              'Keith',
              'Samuel',
              'Willie',
              'Ralph',
              'Lawrence',
              'Nicholas',
              'Roy',
              'Benjamin',
              'Bruce',
              'Brandon',
              'Adam',
              'Harry',
              'Fred',
              'Wayne',
              'Billy',
              'Steve',
              'Louis',
              'Jeremy',
              'Aaron',
              'Randy',
              'Howard',
              'Eugene',
              'Carlos',
              'Russell',
              'Bobby',
              'Victor',
              'Martin',
              'Ernest',
              'Phillip',
              'Todd',
              'Jesse',
              'Craig',
              'Alan',
              'Shawn',
              'Clarence',
              'Sean',
              'Philip',
              'Chris',
              'Johnny',
              'Earl',
              'Jimmy',
              'Antonio',
              'Danny',
              'Bryan',
              'Tony',
              'Luis',
              'Mike',
              'Stanley',
              'Leonard',
              'Nathan',
              'Dale',
              'Manuel',
              'Rodney',
              'Curtis',
              'Norman',
              'Allen',
              'Marvin',
              'Vincent',
              'Glenn',
              'Jeffery',
              'Travis',
              'Jeff',
              'Chad',
              'Jacob',
              'Lee',
              'Melvin',
              'Alfred',
              'Kyle',
              'Francis',
              'Bradley',
              'Jesus',
              'Herbert',
              'Frederick',
              'Ray',
              'Joel',
              'Edwin',
              'Don',
              'Eddie',
              'Ricky',
              'Troy',
              'Randall',
              'Barry',
              'Alexander',
              'Bernard',
              'Mario',
              'Leroy',
              'Francisco',
              'Marcus',
              'Micheal',
              'Theodore',
              'Clifford',
              'Miguel',
              'Oscar',
              'Jay',
              'Jim',
              'Tom',
              'Calvin',
              'Alex',
              'Jon',
              'Ronnie',
              'Bill',
              'Lloyd',
              'Tommy',
              'Leon',
              'Derek',
              'Warren',
              'Darrell',
              'Jerome',
              'Floyd',
              'Leo',
              'Alvin',
              'Tim',
              'Wesley',
              'Gordon',
              'Dean',
              'Greg',
              'Jorge',
              'Dustin',
              'Pedro',
              'Derrick',
              'Dan',
              'Lewis',
              'Zachary',
              'Corey',
              'Herman',
              'Maurice',
              'Vernon',
              'Roberto',
              'Clyde',
              'Glen',
              'Hector',
              'Shane',
              'Ricardo',
              'Sam',
              'Rick',
              'Lester',
              'Brent',
              'Ramon',
              'Charlie',
              'Tyler',
              'Gilbert',
              'Gene',
              'Marc',
              'Reginald',
              'Ruben',
              'Brett',
              'Angel',
              'Nathaniel',
              'Rafael',
              'Leslie',
              'Edgar',
              'Milton',
              'Raul',
              'Ben',
              'Chester',
              'Cecil',
              'Duane',
              'Franklin',
              'Andre',
              'Elmer',
              'Brad',
              'Gabriel',
              'Ron',
              'Mitchell',
              'Roland',
              'Arnold',
              'Harvey',
              'Jared',
              'Adrian',
              'Karl',
              'Cory',
              'Claude',
              'Erik',
              'Darryl',
              'Jamie',
              'Neil',
              'Jessie',
              'Christian',
              'Javier',
              'Fernando',
              'Clinton',
              'Ted',
              'Mathew',
              'Tyrone',
              'Darren',
              'Lonnie',
              'Lance',
              'Cody',
              'Julio',
              'Kelly',
              'Kurt',
              'Allan',
              'Nelson',
              'Guy',
              'Clayton',
              'Hugh',
              'Max',
              'Dwayne',
              'Dwight',
              'Armando',
              'Felix',
              'Jimmie',
              'Everett',
              'Jordan',
              'Ian',
              'Wallace',
              'Ken',
              'Bob',
              'Jaime',
              'Casey',
              'Alfredo',
              'Alberto',
              'Dave',
              'Ivan',
              'Johnnie',
              'Sidney',
              'Byron',
              'Julian',
              'Isaac',
              'Morris',
              'Clifton',
              'Willard',
              'Daryl',
              'Ross',
              'Virgil',
              'Andy',
              'Marshall',
              'Salvador',
              'Perry',
              'Kirk',
              'Sergio',
              'Marion',
              'Tracy',
              'Seth',
              'Kent',
              'Terrance',
              'Rene',
              'Eduardo',
              'Terrence',
              'Enrique',
              'Freddie',
              'Wade']

female_names = ['Mary',
                'Patricia',
                'Linda',
                'Barbara',
                'Elizabeth',
                'Jennifer',
                'Maria',
                'Susan',
                'Margaret',
                'Dorothy',
                'Lisa',
                'Nancy',
                'Karen',
                'Betty',
                'Helen',
                'Sandra',
                'Donna',
                'Carol',
                'Ruth',
                'Sharon',
                'Michelle',
                'Laura',
                'Sarah',
                'Kimberly',
                'Deborah',
                'Jessica',
                'Shirley',
                'Cynthia',
                'Angela',
                'Melissa',
                'Brenda',
                'Amy',
                'Anna',
                'Rebecca',
                'Virginia',
                'Kathleen',
                'Pamela',
                'Martha',
                'Debra',
                'Amanda',
                'Stephanie',
                'Carolyn',
                'Christine',
                'Marie',
                'Janet',
                'Catherine',
                'Frances',
                'Ann',
                'Joyce',
                'Diane',
                'Alice',
                'Julie',
                'Heather',
                'Teresa',
                'Doris',
                'Gloria',
                'Evelyn',
                'Jean',
                'Cheryl',
                'Mildred',
                'Katherine',
                'Joan',
                'Ashley',
                'Judith',
                'Rose',
                'Janice',
                'Kelly',
                'Nicole',
                'Judy',
                'Christina',
                'Kathy',
                'Theresa',
                'Beverly',
                'Denise',
                'Tammy',
                'Irene',
                'Jane',
                'Lori',
                'Rachel',
                'Marilyn',
                'Andrea',
                'Kathryn',
                'Louise',
                'Sara',
                'Anne',
                'Jacqueline',
                'Wanda',
                'Bonnie',
                'Julia',
                'Ruby',
                'Lois',
                'Tina',
                'Phyllis',
                'Norma',
                'Paula',
                'Diana',
                'Annie',
                'Lillian',
                'Emily',
                'Robin',
                'Peggy',
                'Crystal',
                'Gladys',
                'Rita',
                'Dawn',
                'Connie',
                'Florence',
                'Tracy',
                'Edna',
                'Tiffany',
                'Carmen',
                'Rosa',
                'Cindy',
                'Grace',
                'Wendy',
                'Victoria',
                'Edith',
                'Kim',
                'Sherry',
                'Sylvia',
                'Josephine',
                'Thelma',
                'Shannon',
                'Sheila',
                'Ethel',
                'Ellen',
                'Elaine',
                'Marjorie',
                'Carrie',
                'Charlotte',
                'Monica',
                'Esther',
                'Pauline',
                'Emma',
                'Juanita',
                'Anita',
                'Rhonda',
                'Hazel',
                'Amber',
                'Eva',
                'Debbie',
                'April',
                'Leslie',
                'Clara',
                'Lucille',
                'Jamie',
                'Joanne',
                'Eleanor',
                'Valerie',
                'Danielle',
                'Megan',
                'Alicia',
                'Suzanne',
                'Michele',
                'Gail',
                'Bertha',
                'Darlene',
                'Veronica',
                'Jill',
                'Erin',
                'Geraldine',
                'Lauren',
                'Cathy',
                'Joann',
                'Lorraine',
                'Lynn',
                'Sally',
                'Regina',
                'Erica',
                'Beatrice',
                'Dolores',
                'Bernice',
                'Audrey',
                'Yvonne',
                'Annette',
                'June',
                'Samantha',
                'Marion',
                'Dana',
                'Stacy',
                'Ana',
                'Renee',
                'Ida',
                'Vivian',
                'Roberta',
                'Holly',
                'Brittany',
                'Melanie',
                'Loretta',
                'Yolanda',
                'Jeanette',
                'Laurie',
                'Katie',
                'Kristen',
                'Vanessa',
                'Alma',
                'Sue',
                'Elsie',
                'Beth',
                'Jeanne',
                'Vicki',
                'Carla',
                'Tara',
                'Rosemary',
                'Eileen',
                'Terri',
                'Gertrude',
                'Lucy',
                'Tonya',
                'Ella',
                'Stacey',
                'Wilma',
                'Gina',
                'Kristin',
                'Jessie',
                'Natalie',
                'Agnes',
                'Vera',
                'Willie',
                'Charlene',
                'Bessie',
                'Delores',
                'Melinda',
                'Pearl',
                'Arlene',
                'Maureen',
                'Colleen',
                'Allison',
                'Tamara',
                'Joy',
                'Georgia',
                'Constance',
                'Lillie',
                'Claudia',
                'Jackie',
                'Marcia',
                'Tanya',
                'Nellie',
                'Minnie',
                'Marlene',
                'Heidi',
                'Glenda',
                'Lydia',
                'Viola',
                'Courtney',
                'Marian',
                'Stella',
                'Caroline',
                'Dora',
                'Jo',
                'Vickie',
                'Mattie',
                'Terry',
                'Maxine',
                'Irma',
                'Mabel',
                'Marsha',
                'Myrtle',
                'Lena',
                'Christy',
                'Deanna',
                'Patsy',
                'Hilda',
                'Gwendolyn',
                'Jennie',
                'Nora',
                'Margie',
                'Nina',
                'Cassandra',
                'Leah',
                'Penny',
                'Kay',
                'Priscilla',
                'Naomi',
                'Carole',
                'Brandy',
                'Olga',
                'Billie',
                'Dianne',
                'Tracey',
                'Leona',
                'Jenny',
                'Felicia',
                'Sonia',
                'Miriam',
                'Velma',
                'Becky',
                'Bobbie',
                'Violet',
                'Kristina',
                'Toni',
                'Misty',
                'Mae',
                'Shelly',
                'Daisy',
                'Ramona',
                'Sherri',
                'Erika',
                'Katrina',
                'Claire',
                'Lindsey',
                'Lindsay',
                'Geneva',
                'Guadalupe',
                'Belinda',
                'Margarita',
                'Sheryl',
                'Cora',
                'Faye',
                'Ada',
                'Natasha',
                'Sabrina',
                'Isabel',
                'Marguerite',
                'Hattie',
                'Harriet',
                'Molly',
                'Cecilia',
                'Kristi',
                'Brandi',
                'Blanche',
                'Sandy',
                'Rosie',
                'Joanna',
                'Iris',
                'Eunice',
                'Angie',
                'Inez',
                'Lynda',
                'Madeline',
                'Amelia',
                'Alberta',
                'Genevieve',
                'Monique',
                'Jodi',
                'Janie',
                'Maggie',
                'Kayla',
                'Sonya',
                'Jan',
                'Lee',
                'Kristine',
                'Candace',
                'Fannie',
                'Maryann',
                'Opal',
                'Alison',
                'Yvette',
                'Melody',
                'Luz',
                'Susie',
                'Olivia',
                'Flora',
                'Shelley',
                'Kristy',
                'Mamie',
                'Lula',
                'Lola',
                'Verna',
                'Beulah',
                'Antoinette',
                'Candice',
                'Juana']

name_list = female_names + male_names

professions = ['accountant',
               'baker',
               'barber',
               'bartender',
               'builder',
               'butcher',
               'carpenter',
               'cashier',
               'chef',
               'cleaner',
               'dentist',
               'doctor',
               'electrician',
               'engineer',
               'fireman',
               'flight attendant',
               'hairdresser',
               'journalist',
               'judge',
               'lawyer',
               'musician',
               'nurse',
               'painter',
               'photographer',
               'pilot',
               'plumber',
               'cop',
               'receptionist',
               'scientist',
               'secretary',
               'tailor',
               'technician',
               'vet']

verbs_third_person_past = ["was",
                           "beat",
                           "became",
                           "began",
                           "bent",
                           "bet",
                           "blew",
                           "broke",
                           "brought",
                           "built",
                           "burned",
                           "bought",
                           "caught",
                           "chose",
                           "came",
                           "cut",
                           "dug",
                           "did",
                           "drew",
                           "dreamed",
                           "drove",
                           "drank",
                           "ate",
                           "fell",
                           "felt",
                           "fought",
                           "found",
                           "flew",
                           "forgot",
                           "forgave",
                           "froze",
                           "got",
                           "gave",
                           "went",
                           "grew",
                           "hung",
                           "had",
                           "heard",
                           "hid",
                           "hit",
                           "held",
                           "hurt",
                           "kept",
                           "knew",
                           "laid",
                           "led",
                           "left",
                           "lent",
                           "let",
                           "lost",
                           "made",
                           "met",
                           "paid",
                           "put",
                           "read",
                           "rode",
                           "ran",
                           "said",
                           "saw",
                           "sold",
                           "sent",
                           "showed",
                           "shut",
                           "sang",
                           "sat",
                           "slept",
                           "spoke",
                           "spent",
                           "stood",
                           "swam",
                           "took",
                           "taught",
                           "told",
                           "thought",
                           "threw",
                           "understood",
                           "woke",
                           "wore",
                           "won",
                           "wrote"]


verbs_third_person_past_CONTEXT = {"was":["a PRED person",
                                          "the first in line",
                                          "a fan of PERSON's work"],
                                   "beat":["PERSON out of 20 dollars",
                                          "us a lot",
                                          "her", "him"],
                                   "became":["PERSON best friend",
                                          "the most important PROFESSION in this town",
                                          "very important to me"],
                                   "began":["crying", "screaming", "laughing",],
                                   "bent":["the COLOR rod",
                                           "the rules of the soccer game",
                                           "the rules of the card game"],
                                   "bet":["on the wining horse",
                                           "on the COLOR car",
                                           "on the game"],
                                   "blew":["it",
                                           "me off",
                                           "it when he didn't invest in Amazon"],
                                   "broke" : ["the rules", "PERSON's heart", "the record"],
                                   "brought" : ["me out of PERSON's house"],
                                   "built" : ["a computer",
                                            "PERSON's house",
                                            "an airplane",
                                            "an altar for PERSON"],
                                   "burned" : ["the flag",
                                             "PERSON's house",
                                             "some calories"],
                                   "bought" : ["a watch",
                                             "a COLOR car",
                                             "a COLOR bicycle"],
                                   "caught" : ["a COLOR fish"],
                                   "chose" : ["this soccer team",
                                            "to live in CITY",
                                            "this way of life"],
                                   "came":["at night",
                                           "at midnight",
                                           "at noon"],
                                   "cut":["a tree",
                                          "himself",
                                          "my hair"],
                                   "dug":["a hole",
                                          "a hole in PERSON's backyard",
                                          "a hole in the garden"],
                                   "did":["everything",
                                          "it again",
                                           "some good work"],
                                   "drew":["ahead of the other runners"],
                                   "dreamed":["of the playing with PERSON",
                                              "of the being a PROFESSION",
                                              "of running in CITY"],
                                   "drove":["away"
                                            "to the bus stop",
                                            "the truck to PERSON's house"],
                                   "drank":["a bottle of water",
                                            "a bottle of wine",
                                            "a beer", "an orange juice"],
                                   "ate":["an apple", "a steak", "a pizza",
                                          "it all", "breakfast"],
                                   "fell":["to the floor", "off", "in love with PERSON"],
                                   "felt":["an outsider", "a strange", "threatened"],
                                   "fought":["the law", "PERSON", "me"],
                                   "found":["what I was looking for",
                                            "this COLOR car",
                                            "Jesus",
                                            "him",
                                            "her",
                                            "this"
                                            "me"],
                                   "flew":["to CITY"],
                                   "forgot":["about PERSON's past",
                                             "about PERSON's hobby"],
                                   "forgave":["me", "PERSON"],
                                   "froze":["my account",
                                            "PERSON's bank account"],
                                   "got":["me lying", "the money"],
                                   "gave":["PERSON a COLOR car",
                                           "PERSON a COLOR bicycle",
                                           "PERSON a COLOR shirt"],
                                   "went":["to CITY",
                                           "away",
                                           "to PERSON's house"],
                                   "grew":["up",
                                           "up in jail"],
                                   "hung":["up on me", "up on PERSON"],
                                   "had":["a COLOR car",
                                          "a good week",
                                          "a good day"
                                          "a good conversation with PERSON",
                                          "it all",
                                          "everything"],
                                   "heard":["me",
                                            "PERSON",
                                            "my voice"],
                                   "hid":["a smile",
                                          "behind a bush"],
                                   "hit":["a tree", "me", "him", "her"],
                                   "held":["me back", "him close", "her close"],
                                   "hurt":["me", "him", "her"],
                                   "kept":["PERSON's secret from me",
                                           "the game alive",
                                          "saying this was crazy"],
                                   "knew":["about us", "PERSON's secret"],
                                   "laid":["down",
                                           "laid his hands on her",
                                           "laid his hands on him"],
                                   "led":["me to PERSON's house"],
                                   "left":["me waiting", "me", "Barcelona for CITY" ],
                                   "lent":["me some money",
                                           "me some money a month before",
                                           "me PERSON's COLOR bicycle"],
                                   "let":["me drive PERSON's COLOR car",
                                          "this happen",
                                          "use this pen"],
                                   "lost":["PERSON's COLOR car",
                                           "my computer",
                                           "the COLOR car in CITY"],
                                   "made":["me change the way I wrote",
                                           "tea", "coffee"],
                                   "met":["me", "him", "her", "PERSON"],
                                   "paid":["me", "him", "her", "PERSON"],
                                   "put":["the phone down", "PERSON in charge"],
                                   "read":["the book about spiders",
                                           "the news", "a paper"],
                                   "rode":["the horse", "the buffalo"],
                                   "ran":["from me",
                                          "from Barcelona to CITY",
                                          "into PERSON"],
                                   "said":["nice things", "funny things",],
                                   "saw":["a COLOR car running fast",
                                          "the best PROFESSION from CITY",
                                          "me", "him", "her", "PERSON"],
                                   "sold":["me a COLOR car",
                                           "PERSON's bicycle",
                                           "PERSON's house"],
                                   "sent":["me a letter",
                                           "me a note"],
                                   "showed":["my new photos",
                                             "PERSON's old photos"],
                                   "shut":["the door down"],
                                   "sang":["a nice song",
                                           "a pop song"],
                                   "sat":["on the floor",
                                          "on the mat",
                                          "on the chair"],
                                   "slept":["for one day",
                                            "for eight hours",
                                            "the night"],
                                   "spoke":["to me",
                                            "to her about PERSON",
                                            "to him about CITY"],
                                   "spent":["all my money"],
                                   "stood":["up to PERSON",
                                            "he stood in front of the crowd"],
                                   "swam":["out toward the COLOR boat"],
                                   "took":["the footage",
                                           "office",
                                           "a summer job",
                                           "the COLOR shirt out of the washer"],
                                   "taught":["middle school science",
                                             "PERSON about songwriting",
                                             "math"],
                                   "told":["me everything",
                                           "me PERSON's secret",
                                           "me about the bars in CITY"],
                                   "thought":["PERSON was going to die", 
                                              "I was living in CITY",
                                              "I was helping PERSON"],
                                   "threw":["everything out the window"],
                                   "understood":["what I said",
                                                 "what PERSON comment about CITY" ],
                                   "woke":["up"],
                                   "wore":["a COLOR hat", "a COLOR jacket"],
                                   "won":["the game", "the soccer match"],
                                   "wrote":["me a letter",
                                            "me an email",
                                            "a song about the sky",
                                            "me about PERSON"]}


verbs_third_person_past_infinitiv_neg = {"was":"wasn't",
                                         "beat":"didn't beat",
                                         "became":"didn't become",
                                         "began":"didn't begin",
                                         "bent":"didn't bend",
                                         "bet": "didn't bet",
                                         "blew":"didn't blow",
                                         "broke" : "didn't break",
                                         "brought" :"didn't bring",
                                         "built" : "didn't build",
                                         "burned" : "didn't burn", 
                                         "bought" : "didn't buy",
                                         "caught" : "didn't catch",
                                         "chose" : "didn't choose",
                                         "came" : "didn't come",
                                         "cut" : "didn't cut",
                                         "dug" : "didn't dig",
                                         "did" : "didn't do",
                                         "drew" : "didn't draw",
                                         "dreamed" : "didn't dream",
                                         "drove" : "didn't drive",
                                         "drank" : "didn't drink",
                                         "ate" : "didn't eat",
                                         "fell": "didn't fall",
                                         "felt" : "didn't feel",
                                         "fought": "didn't fight",
                                         "found" : "didn't find",
                                         "flew" : "didn't fly",
                                         "forgot": "didn't forget",
                                         "forgave": "didn't forgive",
                                         "froze": "didn't freeze",
                                         "got": "didn't get",
                                         "gave": "didn't give",
                                         "went": "didn't go",
                                         "grew": "didn't grow",
                                         "hung": "didn't hang",
                                         "heard": "didn't hear",
                                         "had": "didn't have",
                                         "hid": "didn't hide",
                                         "hit": "didn't hit",
                                         "held": "didn't hold",
                                         "hurt": "didn't hurt",
                                         "kept": "didn't keep",
                                         "knew": "didn't know",
                                         "laid": "didn't lay",
                                         "led": "didn't lead",
                                         "left": "didn't leave",
                                         "lent": "didn't lend",
                                         "let": "didn't let",
                                         "lost": "didn't lose",
                                         "made": "didn't make",
                                         "met": "didn't meet",
                                         "paid": "didn't pay",
                                         "put": "didn't put",
                                         "read": "didn't read",
                                         "rode": "didn't ride",
                                         "ran": "didn't ring",
                                         "said": "didn't say",
                                         "saw": "didn't see",
                                         "sold": "didn't sell",
                                         "sent": "didn't send",
                                         "showed": "didn't show",
                                         "shut": "didn't shut",
                                         "sang": "didn't sing",
                                         "sat": "didn't sit",
                                         "slept": "didn't sleep",
                                         "spoke": "didn't speak",
                                         "spent": "didn't spend",
                                         "stood": "didn't stand",
                                         "swam": "didn't swim",
                                         "took": "didn't take",
                                         "taught": "didn't teach",
                                         "told": "didn't tell",
                                         "thought": "didn't think",
                                         "threw": "didn't throw",
                                         "understood": "didn't understand",
                                         "woke": "didn't wake",
                                         "wore": "didn't wear",
                                         "won": "didn't win",
                                         "wrote": "didn't write"}


